### ISSUE TITLE
Option for numbered sections in Notebook

### ISSUE THREAD

**Issue by computo-fc** [ipython/ipython#4097]
For writing interactive texts, lecture notes, books etc., it would be very useful (actually, crucial) to have heading cells which give numbered sections and subsections. (This  happens, for example, with the default LaTeX output; but for interactive documents it is needed in notebooks themselves.)

I presume that this is something that can be changed with CSS?  But I expect that this would be useful to a large number of people, so maybe it could be a configuration option for the Notebook?

**Comment by yoki** [comment]
I made it working with custom.css by fixing code by @dpsanders
```css
body {
  counter-reset: section subsection;
}

h1 {
  counter-reset: subsection;
}

h1:before {
    counter-increment: section;
    content: "Section " counter(section) ". ";
}

h2:before {
    counter-increment: subsection;
    content: counter(section) "." counter(subsection) " ";
}
```
