### ISSUE TITLE
Functional aesthetic change edit_mode div class border

### ISSUE THREAD

**Issue by kevindavenport** [ipython/ipython#5513]
I believe the green edit box border should be more distinct to allow users to better differentiate between edit and command mode. This would also encourage the new behavior of having to press enter when creating a new cell (above/below).

In style.css:

From: 

``` css
edit mode div.cell.edit_mode{border-radius:4px;border: light solid #008000 }
```

To

``` css
edit mode div.cell.edit_mode{border-radius:4px;border: medium solid #008000 }
```

![screen shot 2014-04-03 at 11 33 04 am](https://cloud.githubusercontent.com/assets/1929051/2607588/676fd986-bb5f-11e3-8a4b-c1ba982cbbba.png)
