### ISSUE TITLE
Ipython qtconsole segmentation fault with custom stylesheet for IPythonWidget

### ISSUE THREAD

**Issue by astromancer** [ipython/ipython#7001]
I tried a custom stylesheet to change the background of the qtconsole:  In my "ipython_qtconsole_config.py" file I did this:

c.IPythonWidget.style_sheet = '''QPlainTextEdit, QTextEdit { 
                                    background-image: url(/home/apodemus/Pictures/amazing clouds 187.jpg);
                                    }'''

The application launches, and looks great with a pretty background, but as soon as I try to run anything (even just hitting return), it crashes with segfault.

Using: Python 3.4.2; IPython 2.3.1; Ubuntu 12.04

**Comment by astromancer** [comment]
This no longer seems to be an issue.  Custom background can be set by adding the following line to `jupyter_console_config.py`:
```python
c.JupyterQtConsoleApp.stylesheet = '/path/to/style_sheet.css'
```
With `/path/to/style_sheet.css` containing
```css
QPlainTextEdit, QTextEdit { 
    background-image: url(/path/to/image.jpg);
                           }
```
