### ISSUE TITLE
Notebook scrolling look and feel

### ISSUE THREAD

**Issue by juhasch** [ipython/ipython#7372]
When I open a new notebook it looks like this:
![empty](https://cloud.githubusercontent.com/assets/2445216/5607184/b45da3c0-9450-11e4-925e-f3b6039de355.png)

It has a scrollbar, although the new document only has a single empty cell. 

If I then press "SHIFT+ENTER", the newly created cell is scrolled below the toolbar without any need for it:
![shift-enter](https://cloud.githubusercontent.com/assets/2445216/5607205/609a3586-9451-11e4-9b0f-a84aee3c0b34.png)

If I add a lot of new cells, there is always a lot of white space at the bottom:
![space](https://cloud.githubusercontent.com/assets/2445216/5607203/433dcc5a-9451-11e4-89af-168a1f6f4a44.png)

For now I am adding  this to my `custom.css` to make it look and behave better:
```CSS

.end_space {
  height: 20px;
}

body {
  background-color: #eeeeee;
}

@media not print {
  div#site {
    background-color: #ffffff;
  }
  
  div#notebook_panel {
  background-color: #eeeeee;
    min-height: 20vh;
  }
}  

@media not print {
  #notebook-container {    
    min-height: 20vh;
  }
}
```

I don't know what I am doing extactly here. So, what should be done to improve the behaviour of the notebook ?
